import type { Row } from './types';

// Premier League 2024-25 — final table + squads. Champion: Liverpool, 84 pts
// (Arne Slot's first season). Promoted: Leicester, Ipswich, Southampton.
export const S2024: Row[] = [
  { id: 'liverpool', name: 'Liverpool', pts: 84, gf: 86, ga: 41, squad: [
    ['Alisson', 'GK', 90], ['Caoimhín Kelleher', 'GK', 78],
    ['Virgil van Dijk', 'DEF', 92, 'CB'], ['Ibrahima Konaté', 'DEF', 85, 'CB'], ['Jarell Quansah', 'DEF', 79, 'CB'],
    ['Trent Alexander-Arnold', 'DEF', 87, 'RB'], ['Andrew Robertson', 'DEF', 85, 'LB'], ['Joe Gomez', 'DEF', 81, 'CB,RB'], ['Kostas Tsimikas', 'DEF', 79, 'LB'],
    ['Alexis Mac Allister', 'MID', 86, 'CM'], ['Ryan Gravenberch', 'MID', 84, 'CDM'], ['Dominik Szoboszlai', 'MID', 84, 'CM'],
    ['Curtis Jones', 'MID', 81, 'CM'], ['Wataru Endō', 'MID', 79, 'CDM'], ['Harvey Elliott', 'MID', 79, 'CAM'],
    ['Mohamed Salah', 'FWD', 93, 'RW'], ['Luis Díaz', 'FWD', 85, 'LW'], ['Cody Gakpo', 'FWD', 84, 'LW'], ['Diogo Jota', 'FWD', 83, 'ST'], ['Darwin Núñez', 'FWD', 82, 'ST'], ['Federico Chiesa', 'FWD', 80, 'RW'],
  ]},
  { id: 'arsenal', name: 'Arsenal', pts: 74, gf: 69, ga: 34, squad: [
    ['David Raya', 'GK', 85], ['Neto', 'GK', 77],
    ['William Saliba', 'DEF', 88, 'CB'], ['Gabriel Magalhães', 'DEF', 87, 'CB'], ['Jakub Kiwior', 'DEF', 80, 'CB,LB'],
    ['Ben White', 'DEF', 84, 'RB'], ['Jurriën Timber', 'DEF', 82, 'RB,CB'], ['Riccardo Calafiori', 'DEF', 82, 'LB,CB'], ['Myles Lewis-Skelly', 'DEF', 78, 'LB'],
    ['Declan Rice', 'MID', 87, 'CM'], ['Martin Ødegaard', 'MID', 87, 'CAM'], ['Mikel Merino', 'MID', 83, 'CM'],
    ['Thomas Partey', 'MID', 82, 'CDM'], ['Jorginho', 'MID', 80, 'CDM'], ['Ethan Nwaneri', 'MID', 78, 'CAM'],
    ['Bukayo Saka', 'FWD', 88, 'RW'], ['Kai Havertz', 'FWD', 84, 'ST'], ['Gabriel Martinelli', 'FWD', 84, 'LW'], ['Leandro Trossard', 'FWD', 82, 'LW'], ['Raheem Sterling', 'FWD', 80, 'LW'], ['Gabriel Jesus', 'FWD', 82, 'ST'],
  ]},
  { id: 'manchestercity', name: 'Manchester City', pts: 71, gf: 72, ga: 44, squad: [
    ['Ederson', 'GK', 88], ['Stefan Ortega', 'GK', 79],
    ['Rúben Dias', 'DEF', 88, 'CB'], ['Joško Gvardiol', 'DEF', 85, 'CB,LB'], ['Manuel Akanji', 'DEF', 84, 'CB'],
    ['John Stones', 'DEF', 84, 'CB'], ['Kyle Walker', 'DEF', 83, 'RB'], ['Nathan Aké', 'DEF', 83, 'CB,LB'], ['Rico Lewis', 'DEF', 79, 'RB'],
    ['Rodri', 'MID', 90, 'CDM'], ['Kevin De Bruyne', 'MID', 92, 'CAM'], ['Bernardo Silva', 'MID', 87, 'CM'],
    ['Phil Foden', 'MID', 88, 'CAM,LW'], ['Mateo Kovačić', 'MID', 83, 'CM'], ['İlkay Gündoğan', 'MID', 83, 'CM'], ['Nico González', 'MID', 79, 'CDM'],
    ['Erling Haaland', 'FWD', 93, 'ST'], ['Savinho', 'FWD', 82, 'RW'], ['Jérémy Doku', 'FWD', 83, 'LW'], ['Jack Grealish', 'FWD', 82, 'LW'], ['Omar Marmoush', 'FWD', 83, 'FWD'],
  ]},
  { id: 'chelsea', name: 'Chelsea', pts: 69, gf: 64, ga: 43, squad: [
    ['Robert Sánchez', 'GK', 80], ['Filip Jörgensen', 'GK', 77],
    ['Levi Colwill', 'DEF', 82, 'CB'], ['Wesley Fofana', 'DEF', 83, 'CB'], ['Tosin Adarabioyo', 'DEF', 80, 'CB'],
    ['Reece James', 'DEF', 84, 'RB'], ['Marc Cucurella', 'DEF', 82, 'LB'], ['Malo Gusto', 'DEF', 80, 'RB'], ['Renato Veiga', 'DEF', 78, 'CB,LB'],
    ['Cole Palmer', 'MID', 88, 'CAM'], ['Enzo Fernández', 'MID', 85, 'CM'], ['Moisés Caicedo', 'MID', 85, 'CDM'],
    ['Romeo Lavia', 'MID', 80, 'CDM'], ['Kiernan Dewsbury-Hall', 'MID', 78, 'CM'],
    ['Nicolas Jackson', 'FWD', 81, 'ST'], ['Pedro Neto', 'FWD', 83, 'RW'], ['Jadon Sancho', 'FWD', 81, 'LW'], ['Noni Madueke', 'FWD', 80, 'RW'], ['João Félix', 'FWD', 80, 'FWD'], ['Christopher Nkunku', 'FWD', 83, 'FWD'],
  ]},
  { id: 'newcastleunited', name: 'Newcastle United', pts: 66, gf: 68, ga: 47, squad: [
    ['Nick Pope', 'GK', 82], ['Martin Dúbravka', 'GK', 78],
    ['Sven Botman', 'DEF', 82, 'CB'], ['Fabian Schär', 'DEF', 82, 'CB'], ['Dan Burn', 'DEF', 80, 'CB,LB'],
    ['Kieran Trippier', 'DEF', 82, 'RB'], ['Lewis Hall', 'DEF', 79, 'LB'], ['Tino Livramento', 'DEF', 79, 'RB'], ['Jamaal Lascelles', 'DEF', 77, 'CB'],
    ['Bruno Guimarães', 'MID', 87, 'CM'], ['Sandro Tonali', 'MID', 83, 'CM'], ['Joelinton', 'MID', 83, 'CM'],
    ['Joe Willock', 'MID', 79, 'CM'], ['Sean Longstaff', 'MID', 78, 'CM'], ['Jacob Murphy', 'MID', 80, 'RW'],
    ['Alexander Isak', 'FWD', 88, 'ST'], ['Anthony Gordon', 'FWD', 84, 'LW'], ['Callum Wilson', 'FWD', 80, 'ST'], ['Harvey Barnes', 'FWD', 80, 'LW'],
  ]},
  { id: 'astonvilla', name: 'Aston Villa', pts: 66, gf: 58, ga: 51, squad: [
    ['Emiliano Martínez', 'GK', 85], ['Robin Olsen', 'GK', 74],
    ['Pau Torres', 'DEF', 83, 'CB'], ['Ezri Konsa', 'DEF', 82, 'CB'], ['Tyrone Mings', 'DEF', 79, 'CB'],
    ['Matty Cash', 'DEF', 81, 'RB'], ['Lucas Digne', 'DEF', 79, 'LB'], ['Ian Maatsen', 'DEF', 79, 'LB'],
    ['Youri Tielemans', 'MID', 82, 'CM'], ['Boubacar Kamara', 'MID', 82, 'CDM'], ['John McGinn', 'MID', 83, 'CM'],
    ['Morgan Rogers', 'MID', 82, 'CAM'], ['Amadou Onana', 'MID', 82, 'CDM'], ['Leon Bailey', 'MID', 82, 'RW'], ['Marco Asensio', 'MID', 82, 'CAM'],
    ['Ollie Watkins', 'FWD', 85, 'ST'], ['Marcus Rashford', 'FWD', 83, 'LW'], ['Jhon Durán', 'FWD', 80, 'ST'],
  ]},
  { id: 'nottinghamforest', name: 'Nottingham Forest', pts: 65, gf: 58, ga: 46, squad: [
    ['Matz Sels', 'GK', 81], ['Carlos Miguel', 'GK', 75],
    ['Murillo', 'DEF', 83, 'CB'], ['Nikola Milenković', 'DEF', 82, 'CB'], ['Morato', 'DEF', 78, 'CB'],
    ['Ola Aina', 'DEF', 80, 'RB'], ['Neco Williams', 'DEF', 79, 'LB'], ['Nicolás Domínguez', 'DEF', 77, 'CDM'],
    ['Morgan Gibbs-White', 'MID', 83, 'CAM'], ['Elliot Anderson', 'MID', 81, 'CM'], ['Ibrahim Sangaré', 'MID', 80, 'CDM'],
    ['Ryan Yates', 'MID', 77, 'CM'], ['Anthony Elanga', 'MID', 81, 'RW'], ['Callum Hudson-Odoi', 'MID', 80, 'LW'],
    ['Chris Wood', 'FWD', 82, 'ST'], ['Taiwo Awoniyi', 'FWD', 79, 'ST'], ['Ramón Sosa', 'FWD', 77, 'LW'],
  ]},
  { id: 'brightonhovealbion', name: 'Brighton & Hove Albion', pts: 61, gf: 66, ga: 59, squad: [
    ['Bart Verbruggen', 'GK', 80], ['Jason Steele', 'GK', 75],
    ['Lewis Dunk', 'DEF', 83, 'CB'], ['Jan Paul van Hecke', 'DEF', 80, 'CB'], ['Adam Webster', 'DEF', 78, 'CB'],
    ['Pervis Estupiñán', 'DEF', 80, 'LB'], ['Joël Veltman', 'DEF', 78, 'RB'], ['Ferdi Kadıoğlu', 'DEF', 80, 'LB,RB'], ['Tariq Lamptey', 'DEF', 77, 'RB'],
    ['Carlos Baleba', 'MID', 81, 'CDM'], ['Mats Wieffer', 'MID', 80, 'CDM'], ['Matt O\'Riley', 'MID', 81, 'CM'],
    ['Kaoru Mitoma', 'MID', 84, 'LW'], ['Yankuba Minteh', 'MID', 80, 'RW'], ['Brajan Gruda', 'MID', 78, 'CAM'],
    ['João Pedro', 'FWD', 82, 'ST,FWD'], ['Danny Welbeck', 'FWD', 81, 'ST'], ['Georginio Rutter', 'FWD', 81, 'FWD'], ['Simon Adingra', 'FWD', 79, 'RW'],
  ]},
  { id: 'afcbournemouth', name: 'AFC Bournemouth', pts: 56, gf: 58, ga: 46, squad: [
    ['Kepa Arrizabalaga', 'GK', 80], ['Mark Travers', 'GK', 74],
    ['Dean Huijsen', 'DEF', 81, 'CB'], ['Illia Zabarnyi', 'DEF', 81, 'CB'], ['Marcos Senesi', 'DEF', 80, 'CB'],
    ['Milos Kerkez', 'DEF', 81, 'LB'], ['Adam Smith', 'DEF', 76, 'RB'], ['Julián Araujo', 'DEF', 77, 'RB'],
    ['Tyler Adams', 'MID', 80, 'CDM'], ['Ryan Christie', 'MID', 79, 'CM'], ['Lewis Cook', 'MID', 78, 'CM'],
    ['Marcus Tavernier', 'MID', 79, 'LM'], ['David Brooks', 'MID', 78, 'RW'],
    ['Evanilson', 'FWD', 82, 'ST'], ['Antoine Semenyo', 'FWD', 82, 'RW'], ['Justin Kluivert', 'FWD', 81, 'LW'], ['Dango Ouattara', 'FWD', 78, 'RW'],
  ]},
  { id: 'brentford', name: 'Brentford', pts: 56, gf: 66, ga: 57, squad: [
    ['Mark Flekken', 'GK', 79], ['Hákon Valdimarsson', 'GK', 74],
    ['Nathan Collins', 'DEF', 80, 'CB'], ['Ethan Pinnock', 'DEF', 79, 'CB'], ['Sepp van den Berg', 'DEF', 78, 'CB'],
    ['Aaron Hickey', 'DEF', 78, 'RB'], ['Rico Henry', 'DEF', 78, 'LB'], ['Mads Roerslev', 'DEF', 76, 'RB'],
    ['Christian Nørgaard', 'MID', 80, 'CDM'], ['Vitaly Janelt', 'MID', 78, 'CM'], ['Mathias Jensen', 'MID', 78, 'CM'],
    ['Mikkel Damsgaard', 'MID', 81, 'CAM'], ['Yehor Yarmoliuk', 'MID', 76, 'CDM'],
    ['Bryan Mbeumo', 'FWD', 85, 'RW'], ['Yoane Wissa', 'FWD', 82, 'FWD'], ['Kevin Schade', 'FWD', 79, 'LW'], ['Keane Lewis-Potter', 'FWD', 78, 'LW'],
  ]},
  { id: 'fulham', name: 'Fulham', pts: 54, gf: 54, ga: 54, squad: [
    ['Bernd Leno', 'GK', 82], ['Benjamin Lecomte', 'GK', 74],
    ['Joachim Andersen', 'DEF', 81, 'CB'], ['Calvin Bassey', 'DEF', 80, 'CB'], ['Issa Diop', 'DEF', 77, 'CB'],
    ['Kenny Tete', 'DEF', 78, 'RB'], ['Antonee Robinson', 'DEF', 82, 'LB'], ['Timothy Castagne', 'DEF', 79, 'RB'],
    ['Sander Berge', 'MID', 81, 'CM'], ['Sasa Lukic', 'MID', 78, 'CDM'], ['Tom Cairney', 'MID', 79, 'CM'],
    ['Emile Smith Rowe', 'MID', 80, 'CAM'], ['Andreas Pereira', 'MID', 80, 'CAM'], ['Alex Iwobi', 'MID', 81, 'LM'],
    ['Raúl Jiménez', 'FWD', 80, 'ST'], ['Rodrigo Muniz', 'FWD', 80, 'ST'], ['Adama Traoré', 'FWD', 79, 'RW'], ['Reiss Nelson', 'FWD', 77, 'LW'],
  ]},
  { id: 'crystalpalace', name: 'Crystal Palace', pts: 53, gf: 51, ga: 51, squad: [
    ['Dean Henderson', 'GK', 80], ['Remi Matthews', 'GK', 73],
    ['Marc Guéhi', 'DEF', 83, 'CB'], ['Maxence Lacroix', 'DEF', 81, 'CB'], ['Chris Richards', 'DEF', 79, 'CB'],
    ['Daniel Muñoz', 'DEF', 81, 'RB'], ['Tyrick Mitchell', 'DEF', 79, 'LB'], ['Nathaniel Clyne', 'DEF', 74, 'RB'],
    ['Eberechi Eze', 'MID', 84, 'CAM'], ['Adam Wharton', 'MID', 81, 'CM'], ['Daichi Kamada', 'MID', 80, 'CM'],
    ['Will Hughes', 'MID', 76, 'CM'], ['Jefferson Lerma', 'MID', 80, 'CDM'], ['Ismaïla Sarr', 'MID', 81, 'RW'],
    ['Jean-Philippe Mateta', 'FWD', 83, 'ST'], ['Eddie Nketiah', 'FWD', 78, 'ST'], ['Jordan Ayew', 'FWD', 77, 'FWD'],
  ]},
  { id: 'everton', name: 'Everton', pts: 48, gf: 42, ga: 44, squad: [
    ['Jordan Pickford', 'GK', 84], ['João Virgínia', 'GK', 73],
    ['Jarrad Branthwaite', 'DEF', 82, 'CB'], ['James Tarkowski', 'DEF', 81, 'CB'], ['Michael Keane', 'DEF', 77, 'CB'],
    ['Vitalii Mykolenko', 'DEF', 79, 'LB'], ['Jake O\'Brien', 'DEF', 78, 'CB,RB'], ['Nathan Patterson', 'DEF', 77, 'RB'], ['Séamus Coleman', 'DEF', 74, 'RB'],
    ['Idrissa Gueye', 'MID', 79, 'CDM'], ['James Garner', 'MID', 78, 'CM'], ['Abdoulaye Doucouré', 'MID', 80, 'CM'],
    ['Orel Mangala', 'MID', 78, 'CM'], ['Dwight McNeil', 'MID', 80, 'LW'], ['Jesper Lindstrøm', 'MID', 78, 'RW'],
    ['Iliman Ndiaye', 'FWD', 81, 'FWD'], ['Dominic Calvert-Lewin', 'FWD', 79, 'ST'], ['Beto', 'FWD', 77, 'ST'],
  ]},
  { id: 'westhamunited', name: 'West Ham United', pts: 43, gf: 46, ga: 62, squad: [
    ['Alphonse Areola', 'GK', 80], ['Łukasz Fabiański', 'GK', 75],
    ['Max Kilman', 'DEF', 80, 'CB'], ['Jean-Clair Todibo', 'DEF', 81, 'CB'], ['Konstantinos Mavropanos', 'DEF', 79, 'CB'],
    ['Aaron Wan-Bissaka', 'DEF', 80, 'RB'], ['Emerson', 'DEF', 79, 'LB'], ['Vladimír Coufal', 'DEF', 78, 'RB'],
    ['Lucas Paquetá', 'MID', 83, 'CAM'], ['Tomáš Souček', 'MID', 80, 'CM'], ['Edson Álvarez', 'MID', 80, 'CDM'],
    ['Guido Rodríguez', 'MID', 79, 'CDM'], ['Mohammed Kudus', 'MID', 83, 'RW'],
    ['Jarrod Bowen', 'FWD', 84, 'RW,ST'], ['Crysencio Summerville', 'FWD', 81, 'LW'], ['Niclas Füllkrug', 'FWD', 80, 'ST'], ['Michail Antonio', 'FWD', 76, 'ST'],
  ]},
  { id: 'manchesterunited', name: 'Manchester United', pts: 42, gf: 44, ga: 54, squad: [
    ['André Onana', 'GK', 82], ['Altay Bayındır', 'GK', 76],
    ['Matthijs de Ligt', 'DEF', 84, 'CB'], ['Lisandro Martínez', 'DEF', 83, 'CB'], ['Leny Yoro', 'DEF', 80, 'CB'],
    ['Noussair Mazraoui', 'DEF', 81, 'RB'], ['Diogo Dalot', 'DEF', 81, 'RB,LB'], ['Luke Shaw', 'DEF', 81, 'LB'], ['Harry Maguire', 'DEF', 80, 'CB'],
    ['Bruno Fernandes', 'MID', 88, 'CAM'], ['Manuel Ugarte', 'MID', 81, 'CDM'], ['Kobbie Mainoo', 'MID', 81, 'CM'],
    ['Casemiro', 'MID', 80, 'CDM'], ['Christian Eriksen', 'MID', 78, 'CM'], ['Mason Mount', 'MID', 80, 'CAM'], ['Amad Diallo', 'MID', 81, 'RW'],
    ['Rasmus Højlund', 'FWD', 80, 'ST'], ['Joshua Zirkzee', 'FWD', 80, 'ST'], ['Alejandro Garnacho', 'FWD', 81, 'LW'],
  ]},
  { id: 'wolverhamptonwanderers', name: 'Wolverhampton Wanderers', pts: 42, gf: 54, ga: 69, squad: [
    ['José Sá', 'GK', 80], ['Sam Johnstone', 'GK', 78],
    ['Toti Gomes', 'DEF', 78, 'CB'], ['Santiago Bueno', 'DEF', 77, 'CB'], ['Craig Dawson', 'DEF', 77, 'CB'], ['Yerson Mosquera', 'DEF', 76, 'CB'],
    ['Nélson Semedo', 'DEF', 79, 'RB'], ['Rayan Aït-Nouri', 'DEF', 80, 'LB'], ['Matt Doherty', 'DEF', 76, 'RB'],
    ['João Gomes', 'MID', 81, 'CM'], ['Mario Lemina', 'MID', 80, 'CM'], ['André', 'MID', 79, 'CDM'],
    ['Pablo Sarabia', 'MID', 79, 'CAM'], ['Jean-Ricner Bellegarde', 'MID', 78, 'RW'],
    ['Matheus Cunha', 'FWD', 84, 'FWD'], ['Jørgen Strand Larsen', 'FWD', 80, 'ST'], ['Hwang Hee-chan', 'FWD', 80, 'FWD'], ['Gonçalo Guedes', 'FWD', 78, 'LW'],
  ]},
  { id: 'tottenhamhotspur', name: 'Tottenham Hotspur', pts: 38, gf: 64, ga: 65, squad: [
    ['Guglielmo Vicario', 'GK', 83], ['Antonín Kinský', 'GK', 76],
    ['Cristian Romero', 'DEF', 86, 'CB'], ['Micky van de Ven', 'DEF', 84, 'CB'], ['Radu Drăgușin', 'DEF', 78, 'CB'],
    ['Pedro Porro', 'DEF', 83, 'RB'], ['Destiny Udogie', 'DEF', 81, 'LB'], ['Djed Spence', 'DEF', 77, 'RB'], ['Archie Gray', 'DEF', 78, 'RB,CM'],
    ['James Maddison', 'MID', 84, 'CAM'], ['Pape Matar Sarr', 'MID', 80, 'CM'], ['Yves Bissouma', 'MID', 81, 'CDM'],
    ['Rodrigo Bentancur', 'MID', 81, 'CM'], ['Lucas Bergvall', 'MID', 78, 'CM'], ['Dejan Kulusevski', 'MID', 84, 'RW'],
    ['Son Heung-min', 'FWD', 87, 'LW,ST'], ['Dominic Solanke', 'FWD', 83, 'ST'], ['Brennan Johnson', 'FWD', 81, 'RW'], ['Richarlison', 'FWD', 80, 'ST'],
  ]},
  { id: 'leicestercity', name: 'Leicester City', pts: 25, gf: 33, ga: 80, squad: [
    ['Mads Hermansen', 'GK', 78], ['Danny Ward', 'GK', 73],
    ['Wout Faes', 'DEF', 78, 'CB'], ['Jannik Vestergaard', 'DEF', 77, 'CB'], ['Conor Coady', 'DEF', 77, 'CB'],
    ['James Justin', 'DEF', 78, 'RB'], ['Victor Kristiansen', 'DEF', 76, 'LB'], ['Ricardo Pereira', 'DEF', 78, 'RB'],
    ['Wilfred Ndidi', 'MID', 80, 'CDM'], ['Harry Winks', 'MID', 78, 'CM'], ['Boubakary Soumaré', 'MID', 77, 'CM'],
    ['Bilal El Khannouss', 'MID', 78, 'CAM'], ['Facundo Buonanotte', 'MID', 78, 'CAM'],
    ['Jamie Vardy', 'FWD', 80, 'ST'], ['Stephy Mavididi', 'FWD', 79, 'LW'], ['Jordan Ayew', 'FWD', 77, 'FWD'], ['Patson Daka', 'FWD', 77, 'ST'],
  ]},
  { id: 'ipswichtown', name: 'Ipswich Town', pts: 22, gf: 36, ga: 82, squad: [
    ['Arijanet Murić', 'GK', 76], ['Christian Walton', 'GK', 74],
    ['Dara O\'Shea', 'DEF', 77, 'CB'], ['Jacob Greaves', 'DEF', 76, 'CB'], ['Luke Woolfenden', 'DEF', 74, 'CB'],
    ['Leif Davis', 'DEF', 77, 'LB'], ['Ben Johnson', 'DEF', 75, 'RB'], ['Axel Tuanzebe', 'DEF', 74, 'CB'],
    ['Sam Morsy', 'MID', 76, 'CDM'], ['Kalvin Phillips', 'MID', 78, 'CDM'], ['Jens Cajuste', 'MID', 77, 'CM'],
    ['Jack Clarke', 'MID', 78, 'LW'], ['Omari Hutchinson', 'MID', 79, 'RW'], ['Conor Chaplin', 'MID', 75, 'CAM'],
    ['Liam Delap', 'FWD', 81, 'ST'], ['Sammie Szmodics', 'FWD', 77, 'FWD'], ['George Hirst', 'FWD', 74, 'ST'],
  ]},
  { id: 'southampton', name: 'Southampton', pts: 12, gf: 26, ga: 86, squad: [
    ['Aaron Ramsdale', 'GK', 80], ['Joe Lumley', 'GK', 72],
    ['Jan Bednarek', 'DEF', 77, 'CB'], ['Taylor Harwood-Bellis', 'DEF', 77, 'CB'], ['Jack Stephens', 'DEF', 75, 'CB'],
    ['Kyle Walker-Peters', 'DEF', 78, 'RB'], ['Ryan Manning', 'DEF', 76, 'LB'], ['Yukinari Sugawara', 'DEF', 77, 'RB'],
    ['Flynn Downes', 'MID', 76, 'CDM'], ['Will Smallbone', 'MID', 75, 'CM'], ['Joe Aribo', 'MID', 77, 'CM'],
    ['Mateus Fernandes', 'MID', 77, 'CM'], ['Tyler Dibling', 'MID', 78, 'RW'],
    ['Adam Armstrong', 'FWD', 78, 'ST'], ['Cameron Archer', 'FWD', 76, 'ST'], ['Ben Brereton Díaz', 'FWD', 76, 'FWD'], ['Paul Onuachu', 'FWD', 75, 'ST'],
  ]},
];
