import type { Row } from './types';

// Premier League 2023-24 — final table + squads (curated from football knowledge,
// same 0–99 scale as the rest of the dataset). Champion: Man City, 91 pts.
export const S2023: Row[] = [
  { id: 'manchestercity', name: 'Manchester City', pts: 91, gf: 96, ga: 34, squad: [
    ['Ederson', 'GK', 89], ['Stefan Ortega', 'GK', 79],
    ['Rúben Dias', 'DEF', 88, 'CB'], ['John Stones', 'DEF', 86, 'CB'], ['Manuel Akanji', 'DEF', 85, 'CB'],
    ['Nathan Aké', 'DEF', 85, 'CB,LB'], ['Kyle Walker', 'DEF', 85, 'RB'], ['Joško Gvardiol', 'DEF', 84, 'LB,CB'], ['Rico Lewis', 'DEF', 78, 'RB'],
    ['Rodri', 'MID', 90, 'CDM'], ['Kevin De Bruyne', 'MID', 94, 'CAM'], ['Bernardo Silva', 'MID', 88, 'CM'],
    ['Phil Foden', 'MID', 89, 'CAM,LW'], ['Mateo Kovačić', 'MID', 83, 'CM'], ['Matheus Nunes', 'MID', 80, 'CM'],
    ['Erling Haaland', 'FWD', 93, 'ST'], ['Julián Álvarez', 'FWD', 85, 'ST'], ['Jérémy Doku', 'FWD', 83, 'LW'], ['Jack Grealish', 'FWD', 84, 'LW'],
  ]},
  { id: 'arsenal', name: 'Arsenal', pts: 89, gf: 91, ga: 29, squad: [
    ['David Raya', 'GK', 84], ['Aaron Ramsdale', 'GK', 82],
    ['William Saliba', 'DEF', 87, 'CB'], ['Gabriel Magalhães', 'DEF', 86, 'CB'], ['Ben White', 'DEF', 85, 'RB,CB'],
    ['Oleksandr Zinchenko', 'DEF', 82, 'LB'], ['Jakub Kiwior', 'DEF', 79, 'CB,LB'], ['Takehiro Tomiyasu', 'DEF', 82, 'RB'], ['Jurriën Timber', 'DEF', 80, 'RB,CB'],
    ['Declan Rice', 'MID', 86, 'CDM'], ['Martin Ødegaard', 'MID', 88, 'CAM'], ['Kai Havertz', 'MID', 84, 'CM'],
    ['Jorginho', 'MID', 82, 'CDM'], ['Thomas Partey', 'MID', 82, 'CDM'], ['Fábio Vieira', 'MID', 78, 'CAM'],
    ['Bukayo Saka', 'FWD', 87, 'RW'], ['Gabriel Martinelli', 'FWD', 85, 'LW'], ['Gabriel Jesus', 'FWD', 84, 'ST'], ['Leandro Trossard', 'FWD', 82, 'LW'], ['Eddie Nketiah', 'FWD', 78, 'ST'],
  ]},
  { id: 'liverpool', name: 'Liverpool', pts: 82, gf: 86, ga: 41, squad: [
    ['Alisson', 'GK', 90], ['Caoimhín Kelleher', 'GK', 78],
    ['Virgil van Dijk', 'DEF', 92, 'CB'], ['Ibrahima Konaté', 'DEF', 84, 'CB'], ['Joël Matip', 'DEF', 82, 'CB'],
    ['Trent Alexander-Arnold', 'DEF', 87, 'RB'], ['Andrew Robertson', 'DEF', 86, 'LB'], ['Joe Gomez', 'DEF', 81, 'CB,RB'], ['Kostas Tsimikas', 'DEF', 79, 'LB'],
    ['Alexis Mac Allister', 'MID', 85, 'CM'], ['Dominik Szoboszlai', 'MID', 84, 'CM,CAM'], ['Wataru Endō', 'MID', 80, 'CDM'],
    ['Curtis Jones', 'MID', 80, 'CM'], ['Ryan Gravenberch', 'MID', 80, 'CM'], ['Harvey Elliott', 'MID', 79, 'CM'],
    ['Mohamed Salah', 'FWD', 93, 'RW'], ['Luis Díaz', 'FWD', 85, 'LW'], ['Diogo Jota', 'FWD', 84, 'ST'], ['Darwin Núñez', 'FWD', 83, 'ST'], ['Cody Gakpo', 'FWD', 83, 'FWD'],
  ]},
  { id: 'astonvilla', name: 'Aston Villa', pts: 68, gf: 76, ga: 61, squad: [
    ['Emiliano Martínez', 'GK', 85], ['Robin Olsen', 'GK', 75],
    ['Pau Torres', 'DEF', 83, 'CB'], ['Ezri Konsa', 'DEF', 81, 'CB'], ['Diego Carlos', 'DEF', 80, 'CB'],
    ['Matty Cash', 'DEF', 81, 'RB'], ['Lucas Digne', 'DEF', 80, 'LB'], ['Álex Moreno', 'DEF', 78, 'LB'],
    ['Douglas Luiz', 'MID', 84, 'CM'], ['Boubacar Kamara', 'MID', 82, 'CDM'], ['John McGinn', 'MID', 83, 'CM'],
    ['Youri Tielemans', 'MID', 81, 'CM'], ['Leon Bailey', 'MID', 82, 'RW'], ['Nicolò Zaniolo', 'MID', 78, 'CAM'],
    ['Ollie Watkins', 'FWD', 85, 'ST'], ['Moussa Diaby', 'FWD', 83, 'RW'], ['Jhon Durán', 'FWD', 76, 'ST'],
  ]},
  { id: 'tottenhamhotspur', name: 'Tottenham Hotspur', pts: 66, gf: 74, ga: 61, squad: [
    ['Guglielmo Vicario', 'GK', 83], ['Fraser Forster', 'GK', 75],
    ['Cristian Romero', 'DEF', 86, 'CB'], ['Micky van de Ven', 'DEF', 83, 'CB'], ['Ben Davies', 'DEF', 79, 'CB'],
    ['Pedro Porro', 'DEF', 82, 'RB'], ['Destiny Udogie', 'DEF', 81, 'LB'], ['Emerson Royal', 'DEF', 78, 'RB'],
    ['James Maddison', 'MID', 85, 'CAM'], ['Yves Bissouma', 'MID', 82, 'CDM'], ['Rodrigo Bentancur', 'MID', 81, 'CM'],
    ['Pape Matar Sarr', 'MID', 79, 'CM'], ['Pierre-Emile Højbjerg', 'MID', 80, 'CDM'], ['Dejan Kulusevski', 'MID', 83, 'RW'],
    ['Son Heung-min', 'FWD', 89, 'LW,ST'], ['Richarlison', 'FWD', 81, 'ST'], ['Brennan Johnson', 'FWD', 80, 'RW'], ['Timo Werner', 'FWD', 80, 'LW'],
  ]},
  { id: 'chelsea', name: 'Chelsea', pts: 63, gf: 77, ga: 63, squad: [
    ['Robert Sánchez', 'GK', 79], ['Đorđe Petrović', 'GK', 77],
    ['Thiago Silva', 'DEF', 82, 'CB'], ['Levi Colwill', 'DEF', 80, 'CB'], ['Axel Disasi', 'DEF', 80, 'CB'],
    ['Reece James', 'DEF', 84, 'RB'], ['Ben Chilwell', 'DEF', 81, 'LB'], ['Marc Cucurella', 'DEF', 79, 'LB'], ['Malo Gusto', 'DEF', 78, 'RB'],
    ['Cole Palmer', 'MID', 86, 'CAM,RW'], ['Enzo Fernández', 'MID', 84, 'CM'], ['Moisés Caicedo', 'MID', 83, 'CDM'],
    ['Conor Gallagher', 'MID', 82, 'CM'], ['Christopher Nkunku', 'MID', 84, 'CAM'],
    ['Nicolas Jackson', 'FWD', 80, 'ST'], ['Raheem Sterling', 'FWD', 84, 'LW'], ['Mykhailo Mudryk', 'FWD', 79, 'LW'], ['Noni Madueke', 'FWD', 78, 'RW'],
  ]},
  { id: 'newcastleunited', name: 'Newcastle United', pts: 60, gf: 85, ga: 62, squad: [
    ['Nick Pope', 'GK', 83], ['Martin Dúbravka', 'GK', 78],
    ['Sven Botman', 'DEF', 82, 'CB'], ['Fabian Schär', 'DEF', 82, 'CB'], ['Dan Burn', 'DEF', 79, 'CB,LB'],
    ['Kieran Trippier', 'DEF', 84, 'RB'], ['Tino Livramento', 'DEF', 78, 'RB'], ['Jamaal Lascelles', 'DEF', 78, 'CB'],
    ['Bruno Guimarães', 'MID', 86, 'CM'], ['Sandro Tonali', 'MID', 82, 'CM'], ['Joelinton', 'MID', 82, 'CM'],
    ['Sean Longstaff', 'MID', 78, 'CM'], ['Joe Willock', 'MID', 79, 'CM'], ['Miguel Almirón', 'MID', 80, 'RW'],
    ['Alexander Isak', 'FWD', 86, 'ST'], ['Anthony Gordon', 'FWD', 83, 'LW'], ['Callum Wilson', 'FWD', 81, 'ST'], ['Harvey Barnes', 'FWD', 80, 'LW'],
  ]},
  { id: 'manchesterunited', name: 'Manchester United', pts: 60, gf: 57, ga: 58, squad: [
    ['André Onana', 'GK', 83], ['Altay Bayındır', 'GK', 76],
    ['Lisandro Martínez', 'DEF', 84, 'CB'], ['Raphaël Varane', 'DEF', 83, 'CB'], ['Harry Maguire', 'DEF', 81, 'CB'],
    ['Diogo Dalot', 'DEF', 81, 'RB'], ['Luke Shaw', 'DEF', 82, 'LB'], ['Victor Lindelöf', 'DEF', 80, 'CB'], ['Aaron Wan-Bissaka', 'DEF', 80, 'RB'],
    ['Bruno Fernandes', 'MID', 88, 'CAM'], ['Casemiro', 'MID', 82, 'CDM'], ['Kobbie Mainoo', 'MID', 80, 'CM'],
    ['Scott McTominay', 'MID', 80, 'CM'], ['Christian Eriksen', 'MID', 80, 'CM'], ['Mason Mount', 'MID', 82, 'CAM'],
    ['Marcus Rashford', 'FWD', 84, 'LW'], ['Rasmus Højlund', 'FWD', 80, 'ST'], ['Alejandro Garnacho', 'FWD', 81, 'LW'], ['Antony', 'FWD', 78, 'RW'],
  ]},
  { id: 'westhamunited', name: 'West Ham United', pts: 52, gf: 60, ga: 74, squad: [
    ['Alphonse Areola', 'GK', 80], ['Łukasz Fabiański', 'GK', 76],
    ['Kurt Zouma', 'DEF', 80, 'CB'], ['Nayef Aguerd', 'DEF', 80, 'CB'], ['Konstantinos Mavropanos', 'DEF', 79, 'CB'],
    ['Vladimír Coufal', 'DEF', 79, 'RB'], ['Aaron Cresswell', 'DEF', 81, 'LB'], ['Emerson', 'DEF', 78, 'LB'],
    ['Lucas Paquetá', 'MID', 84, 'CAM'], ['Edson Álvarez', 'MID', 81, 'CDM'], ['Tomáš Souček', 'MID', 80, 'CM'],
    ['James Ward-Prowse', 'MID', 82, 'CM'], ['Mohammed Kudus', 'MID', 83, 'RW'],
    ['Jarrod Bowen', 'FWD', 85, 'RW,ST'], ['Michail Antonio', 'FWD', 78, 'ST'], ['Danny Ings', 'FWD', 77, 'ST'], ['Saïd Benrahma', 'FWD', 79, 'LW'],
  ]},
  { id: 'crystalpalace', name: 'Crystal Palace', pts: 49, gf: 57, ga: 58, squad: [
    ['Sam Johnstone', 'GK', 79], ['Dean Henderson', 'GK', 79],
    ['Marc Guéhi', 'DEF', 82, 'CB'], ['Joachim Andersen', 'DEF', 81, 'CB'], ['Chris Richards', 'DEF', 77, 'CB'],
    ['Daniel Muñoz', 'DEF', 78, 'RB'], ['Tyrick Mitchell', 'DEF', 79, 'LB'], ['Joel Ward', 'DEF', 76, 'RB'],
    ['Eberechi Eze', 'MID', 84, 'CAM'], ['Jefferson Lerma', 'MID', 81, 'CM'], ['Adam Wharton', 'MID', 79, 'CM'],
    ['Cheick Doucouré', 'MID', 80, 'CDM'], ['Will Hughes', 'MID', 76, 'CM'], ['Michael Olise', 'MID', 84, 'RW'],
    ['Jean-Philippe Mateta', 'FWD', 80, 'ST'], ['Jordan Ayew', 'FWD', 78, 'FWD'], ['Odsonne Édouard', 'FWD', 77, 'ST'],
  ]},
  { id: 'brightonhovealbion', name: 'Brighton & Hove Albion', pts: 48, gf: 55, ga: 62, squad: [
    ['Bart Verbruggen', 'GK', 79], ['Jason Steele', 'GK', 76],
    ['Lewis Dunk', 'DEF', 83, 'CB'], ['Jan Paul van Hecke', 'DEF', 79, 'CB'], ['Igor', 'DEF', 79, 'CB'],
    ['Pervis Estupiñán', 'DEF', 80, 'LB'], ['Tariq Lamptey', 'DEF', 78, 'RB'], ['Joël Veltman', 'DEF', 78, 'RB'],
    ['Pascal Groß', 'MID', 82, 'CM'], ['Billy Gilmour', 'MID', 78, 'CM'], ['Carlos Baleba', 'MID', 78, 'CDM'],
    ['Kaoru Mitoma', 'MID', 84, 'LW'], ['Solly March', 'MID', 80, 'RW'], ['Facundo Buonanotte', 'MID', 77, 'CAM'],
    ['João Pedro', 'FWD', 81, 'ST,FWD'], ['Danny Welbeck', 'FWD', 80, 'ST'], ['Evan Ferguson', 'FWD', 80, 'ST'], ['Simon Adingra', 'FWD', 78, 'RW'],
  ]},
  { id: 'afcbournemouth', name: 'AFC Bournemouth', pts: 48, gf: 54, ga: 67, squad: [
    ['Neto', 'GK', 79], ['Mark Travers', 'GK', 74],
    ['Illia Zabarnyi', 'DEF', 79, 'CB'], ['Marcos Senesi', 'DEF', 79, 'CB'], ['Lloyd Kelly', 'DEF', 78, 'CB'],
    ['Max Aarons', 'DEF', 77, 'RB'], ['Milos Kerkez', 'DEF', 79, 'LB'], ['Adam Smith', 'DEF', 76, 'RB'],
    ['Ryan Christie', 'MID', 78, 'CM'], ['Lewis Cook', 'MID', 77, 'CM'], ['Tyler Adams', 'MID', 79, 'CDM'],
    ['Marcus Tavernier', 'MID', 79, 'LM'], ['Philip Billing', 'MID', 76, 'CM'], ['Antoine Semenyo', 'MID', 79, 'RW'],
    ['Dominic Solanke', 'FWD', 83, 'ST'], ['Justin Kluivert', 'FWD', 79, 'LW'], ['Luis Sinisterra', 'FWD', 79, 'LW'],
  ]},
  { id: 'fulham', name: 'Fulham', pts: 47, gf: 55, ga: 61, squad: [
    ['Bernd Leno', 'GK', 82], ['Marek Rodák', 'GK', 74],
    ['Tosin Adarabioyo', 'DEF', 79, 'CB'], ['Calvin Bassey', 'DEF', 78, 'CB'], ['Issa Diop', 'DEF', 77, 'CB'],
    ['Kenny Tete', 'DEF', 78, 'RB'], ['Antonee Robinson', 'DEF', 80, 'LB'], ['Tim Ream', 'DEF', 76, 'CB'],
    ['João Palhinha', 'MID', 84, 'CDM'], ['Andreas Pereira', 'MID', 80, 'CAM'], ['Tom Cairney', 'MID', 79, 'CM'],
    ['Sasa Lukic', 'MID', 78, 'CM'], ['Harrison Reed', 'MID', 76, 'CDM'], ['Alex Iwobi', 'MID', 80, 'LM'],
    ['Raúl Jiménez', 'FWD', 79, 'ST'], ['Rodrigo Muniz', 'FWD', 78, 'ST'], ['Adama Traoré', 'FWD', 79, 'RW'], ['Willian', 'FWD', 79, 'RW'],
  ]},
  { id: 'wolverhamptonwanderers', name: 'Wolverhampton Wanderers', pts: 46, gf: 50, ga: 65, squad: [
    ['José Sá', 'GK', 81], ['Daniel Bentley', 'GK', 73],
    ['Max Kilman', 'DEF', 80, 'CB'], ['Craig Dawson', 'DEF', 78, 'CB'], ['Toti Gomes', 'DEF', 77, 'CB'],
    ['Nélson Semedo', 'DEF', 79, 'RB'], ['Rayan Aït-Nouri', 'DEF', 79, 'LB'], ['Matt Doherty', 'DEF', 76, 'RB'],
    ['Mario Lemina', 'MID', 80, 'CM'], ['João Gomes', 'MID', 80, 'CM'], ['Pablo Sarabia', 'MID', 80, 'CAM'],
    ['Tommy Doyle', 'MID', 75, 'CM'], ['Pedro Neto', 'MID', 83, 'RW'],
    ['Matheus Cunha', 'FWD', 82, 'FWD'], ['Hwang Hee-chan', 'FWD', 81, 'FWD'], ['Jean-Ricner Bellegarde', 'FWD', 78, 'RW'],
  ]},
  { id: 'everton', name: 'Everton', pts: 40, gf: 40, ga: 51, squad: [
    ['Jordan Pickford', 'GK', 84], ['João Virgínia', 'GK', 73],
    ['Jarrad Branthwaite', 'DEF', 81, 'CB'], ['James Tarkowski', 'DEF', 81, 'CB'], ['Michael Keane', 'DEF', 77, 'CB'],
    ['Nathan Patterson', 'DEF', 77, 'RB'], ['Vitalii Mykolenko', 'DEF', 79, 'LB'], ['Ben Godfrey', 'DEF', 76, 'CB'], ['Seamus Coleman', 'DEF', 75, 'RB'],
    ['Amadou Onana', 'MID', 81, 'CDM'], ['Abdoulaye Doucouré', 'MID', 80, 'CM'], ['Idrissa Gueye', 'MID', 78, 'CDM'],
    ['James Garner', 'MID', 77, 'CM'], ['Dwight McNeil', 'MID', 80, 'LW'], ['Jack Harrison', 'MID', 79, 'RW'],
    ['Dominic Calvert-Lewin', 'FWD', 80, 'ST'], ['Beto', 'FWD', 77, 'ST'],
  ]},
  { id: 'brentford', name: 'Brentford', pts: 39, gf: 56, ga: 65, squad: [
    ['Mark Flekken', 'GK', 79], ['Thomas Strakosha', 'GK', 74],
    ['Ethan Pinnock', 'DEF', 79, 'CB'], ['Nathan Collins', 'DEF', 79, 'CB'], ['Ben Mee', 'DEF', 78, 'CB'],
    ['Aaron Hickey', 'DEF', 78, 'RB'], ['Rico Henry', 'DEF', 79, 'LB'], ['Kristoffer Ajer', 'DEF', 78, 'RB,CB'], ['Mads Roerslev', 'DEF', 76, 'RB'],
    ['Christian Nørgaard', 'MID', 79, 'CDM'], ['Vitaly Janelt', 'MID', 78, 'CM'], ['Mathias Jensen', 'MID', 78, 'CM'],
    ['Mikkel Damsgaard', 'MID', 78, 'CAM'], ['Yoane Wissa', 'FWD', 79, 'FWD'],
    ['Ivan Toney', 'FWD', 84, 'ST'], ['Bryan Mbeumo', 'FWD', 82, 'RW'], ['Neal Maupay', 'FWD', 79, 'ST'], ['Kevin Schade', 'FWD', 76, 'LW'],
  ]},
  { id: 'nottinghamforest', name: 'Nottingham Forest', pts: 32, gf: 49, ga: 67, squad: [
    ['Matz Sels', 'GK', 79], ['Odysseas Vlachodimos', 'GK', 77],
    ['Murillo', 'DEF', 80, 'CB'], ['Nikola Milenković', 'DEF', 80, 'CB'], ['Felipe', 'DEF', 78, 'CB'],
    ['Ola Aina', 'DEF', 78, 'RB'], ['Neco Williams', 'DEF', 78, 'LB'], ['Moussa Niakhaté', 'DEF', 78, 'CB'],
    ['Morgan Gibbs-White', 'MID', 82, 'CAM'], ['Ryan Yates', 'MID', 76, 'CM'], ['Danilo', 'MID', 77, 'CM'],
    ['Nicolás Domínguez', 'MID', 77, 'CDM'], ['Elliot Anderson', 'MID', 78, 'CM'],
    ['Chris Wood', 'FWD', 80, 'ST'], ['Taiwo Awoniyi', 'FWD', 79, 'ST'], ['Callum Hudson-Odoi', 'FWD', 79, 'LW'], ['Anthony Elanga', 'FWD', 79, 'RW'],
  ]},
  { id: 'lutontown', name: 'Luton Town', pts: 26, gf: 52, ga: 85, squad: [
    ['Thomas Kaminski', 'GK', 76], ['Tim Krul', 'GK', 74],
    ['Tom Lockyer', 'DEF', 74, 'CB'], ['Gabriel Osho', 'DEF', 74, 'CB'], ['Teden Mengi', 'DEF', 74, 'CB'], ['Reece Burke', 'DEF', 73, 'CB'],
    ['Alfie Doughty', 'DEF', 74, 'LB'], ['Daiki Hashioka', 'DEF', 72, 'RB'], ["Amari'i Bell", 'DEF', 73, 'LB'],
    ['Ross Barkley', 'MID', 79, 'CM'], ['Marvelous Nakamba', 'MID', 74, 'CDM'], ['Albert Sambi Lokonga', 'MID', 76, 'CM'],
    ['Pelly Ruddock Mpanzu', 'MID', 73, 'CM'], ['Tahith Chong', 'MID', 75, 'RW'],
    ['Carlton Morris', 'FWD', 77, 'ST'], ['Elijah Adebayo', 'FWD', 77, 'ST'], ['Jacob Brown', 'FWD', 74, 'ST'], ['Andros Townsend', 'FWD', 74, 'RW'],
  ]},
  { id: 'burnley', name: 'Burnley', pts: 24, gf: 41, ga: 78, squad: [
    ['James Trafford', 'GK', 76], ['Arijanet Murić', 'GK', 75],
    ["Dara O'Shea", 'DEF', 75, 'CB'], ['Jordan Beyer', 'DEF', 75, 'CB'], ['Maxime Estève', 'DEF', 74, 'CB'], ['Hjalmar Ekdal', 'DEF', 73, 'CB'],
    ['Charlie Taylor', 'DEF', 74, 'LB'], ['Connor Roberts', 'DEF', 74, 'RB'], ['Vitinho', 'DEF', 73, 'RB'],
    ['Josh Brownhill', 'MID', 76, 'CM'], ['Sander Berge', 'MID', 81, 'CM'], ['Josh Cullen', 'MID', 76, 'CDM'],
    ['Aaron Ramsey', 'MID', 74, 'CAM'], ['Wilson Odobert', 'MID', 74, 'LW'],
    ['Lyle Foster', 'FWD', 75, 'ST'], ['Zeki Amdouni', 'FWD', 76, 'ST'], ['Jay Rodriguez', 'FWD', 74, 'ST'], ['Jacob Bruun Larsen', 'FWD', 74, 'RW'],
  ]},
  { id: 'sheffieldunited', name: 'Sheffield United', pts: 16, gf: 35, ga: 104, squad: [
    ['Wes Foderingham', 'GK', 74], ['Ivo Grbić', 'GK', 73],
    ['Anel Ahmedhodžić', 'DEF', 76, 'CB'], ['John Egan', 'DEF', 75, 'CB'], ['Jack Robinson', 'DEF', 74, 'CB'], ['Auston Trusty', 'DEF', 74, 'CB'],
    ['George Baldock', 'DEF', 74, 'RB'], ['Max Lowe', 'DEF', 73, 'LB'],
    ['Gustavo Hamer', 'MID', 78, 'CM'], ['Vinícius Souza', 'MID', 75, 'CDM'], ['Oliver Norwood', 'MID', 75, 'CM'],
    ['James McAtee', 'MID', 77, 'CAM'], ['Ben Osborn', 'MID', 73, 'CM'],
    ['Cameron Archer', 'FWD', 75, 'ST'], ['Oli McBurnie', 'FWD', 75, 'ST'], ['William Osula', 'FWD', 73, 'ST'],
  ]},
];
