import type { Row } from './types';

// Premier League 2025-26 — PROJECTED (post-training-cutoff). The table order and
// some details are estimated; squads carry forward 2024-25 with the major known
// summer-2025 moves. Promoted: Leeds, Burnley, Sunderland. Flagged `estimated`.
export const S2025: Row[] = [
  { id: 'liverpool', name: 'Liverpool', pts: 84, gf: 86, ga: 41, squad: [
    ['Alisson', 'GK', 89], ['Giorgi Mamardashvili', 'GK', 80],
    ['Virgil van Dijk', 'DEF', 91, 'CB'], ['Ibrahima Konaté', 'DEF', 85, 'CB'], ['Jarell Quansah', 'DEF', 79, 'CB'],
    ['Jeremie Frimpong', 'DEF', 82, 'RB'], ['Milos Kerkez', 'DEF', 81, 'LB'], ['Andrew Robertson', 'DEF', 83, 'LB'], ['Joe Gomez', 'DEF', 80, 'CB'],
    ['Florian Wirtz', 'MID', 88, 'CAM'], ['Alexis Mac Allister', 'MID', 86, 'CM'], ['Ryan Gravenberch', 'MID', 85, 'CDM'],
    ['Dominik Szoboszlai', 'MID', 84, 'CM'], ['Curtis Jones', 'MID', 81, 'CM'], ['Wataru Endō', 'MID', 78, 'CDM'],
    ['Mohamed Salah', 'FWD', 92, 'RW'], ['Alexander Isak', 'FWD', 88, 'ST'], ['Hugo Ekitiké', 'FWD', 83, 'ST'], ['Cody Gakpo', 'FWD', 84, 'LW'],
  ]},
  { id: 'arsenal', name: 'Arsenal', pts: 80, gf: 72, ga: 33, squad: [
    ['David Raya', 'GK', 85], ['Kepa Arrizabalaga', 'GK', 78],
    ['William Saliba', 'DEF', 88, 'CB'], ['Gabriel Magalhães', 'DEF', 87, 'CB'], ['Cristhian Mosquera', 'DEF', 79, 'CB'],
    ['Jurriën Timber', 'DEF', 83, 'RB'], ['Riccardo Calafiori', 'DEF', 82, 'LB'], ['Ben White', 'DEF', 83, 'RB'], ['Myles Lewis-Skelly', 'DEF', 80, 'LB'],
    ['Declan Rice', 'MID', 88, 'CM'], ['Martín Zubimendi', 'MID', 84, 'CDM'], ['Martin Ødegaard', 'MID', 87, 'CAM'],
    ['Mikel Merino', 'MID', 82, 'CM'], ['Ethan Nwaneri', 'MID', 80, 'CAM'],
    ['Viktor Gyökeres', 'FWD', 86, 'ST'], ['Bukayo Saka', 'FWD', 88, 'RW'], ['Gabriel Martinelli', 'FWD', 84, 'LW'], ['Eberechi Eze', 'FWD', 84, 'CAM'], ['Noni Madueke', 'FWD', 80, 'RW'], ['Leandro Trossard', 'FWD', 81, 'LW'],
  ]},
  { id: 'manchestercity', name: 'Manchester City', pts: 78, gf: 78, ga: 40, squad: [
    ['James Trafford', 'GK', 80], ['Stefan Ortega', 'GK', 79],
    ['Rúben Dias', 'DEF', 88, 'CB'], ['Joško Gvardiol', 'DEF', 85, 'CB,LB'], ['John Stones', 'DEF', 83, 'CB'],
    ['Manuel Akanji', 'DEF', 83, 'CB'], ['Nathan Aké', 'DEF', 82, 'CB'], ['Rico Lewis', 'DEF', 79, 'RB'], ['Rayan Aït-Nouri', 'DEF', 81, 'LB'],
    ['Rodri', 'MID', 90, 'CDM'], ['Tijjani Reijnders', 'MID', 84, 'CM'], ['Bernardo Silva', 'MID', 86, 'CM'],
    ['Phil Foden', 'MID', 87, 'CAM'], ['Mateo Kovačić', 'MID', 82, 'CM'], ['Nico González', 'MID', 80, 'CDM'], ['Rayan Cherki', 'MID', 82, 'CAM'],
    ['Erling Haaland', 'FWD', 93, 'ST'], ['Omar Marmoush', 'FWD', 84, 'FWD'], ['Savinho', 'FWD', 83, 'RW'], ['Jérémy Doku', 'FWD', 83, 'LW'],
  ]},
  { id: 'chelsea', name: 'Chelsea', pts: 72, gf: 68, ga: 45, squad: [
    ['Robert Sánchez', 'GK', 80], ['Filip Jörgensen', 'GK', 77],
    ['Levi Colwill', 'DEF', 82, 'CB'], ['Wesley Fofana', 'DEF', 83, 'CB'], ['Trevoh Chalobah', 'DEF', 79, 'CB'],
    ['Reece James', 'DEF', 84, 'RB'], ['Marc Cucurella', 'DEF', 83, 'LB'], ['Malo Gusto', 'DEF', 80, 'RB'], ['Tosin Adarabioyo', 'DEF', 80, 'CB'],
    ['Cole Palmer', 'MID', 88, 'CAM'], ['Moisés Caicedo', 'MID', 86, 'CDM'], ['Enzo Fernández', 'MID', 85, 'CM'],
    ['Romeo Lavia', 'MID', 80, 'CDM'], ['Estêvão Willian', 'MID', 81, 'RW'],
    ['João Pedro', 'FWD', 83, 'ST'], ['Liam Delap', 'FWD', 81, 'ST'], ['Pedro Neto', 'FWD', 83, 'RW'], ['Jamie Gittens', 'FWD', 80, 'LW'], ['Christopher Nkunku', 'FWD', 82, 'FWD'],
  ]},
  { id: 'newcastleunited', name: 'Newcastle United', pts: 66, gf: 64, ga: 48, squad: [
    ['Nick Pope', 'GK', 82], ['Aaron Ramsdale', 'GK', 79],
    ['Sven Botman', 'DEF', 82, 'CB'], ['Fabian Schär', 'DEF', 81, 'CB'], ['Malick Thiaw', 'DEF', 80, 'CB'],
    ['Kieran Trippier', 'DEF', 81, 'RB'], ['Lewis Hall', 'DEF', 80, 'LB'], ['Tino Livramento', 'DEF', 80, 'RB'], ['Dan Burn', 'DEF', 79, 'CB'],
    ['Bruno Guimarães', 'MID', 87, 'CM'], ['Sandro Tonali', 'MID', 84, 'CM'], ['Joelinton', 'MID', 83, 'CM'],
    ['Jacob Ramsey', 'MID', 79, 'CM'], ['Joe Willock', 'MID', 79, 'CM'], ['Anthony Elanga', 'MID', 82, 'RW'],
    ['Nick Woltemade', 'FWD', 82, 'ST'], ['Yoane Wissa', 'FWD', 82, 'FWD'], ['Anthony Gordon', 'FWD', 84, 'LW'], ['Harvey Barnes', 'FWD', 80, 'LW'],
  ]},
  { id: 'astonvilla', name: 'Aston Villa', pts: 64, gf: 58, ga: 50, squad: [
    ['Emiliano Martínez', 'GK', 84], ['Marco Bizot', 'GK', 76],
    ['Pau Torres', 'DEF', 82, 'CB'], ['Ezri Konsa', 'DEF', 82, 'CB'], ['Tyrone Mings', 'DEF', 78, 'CB'],
    ['Matty Cash', 'DEF', 80, 'RB'], ['Lucas Digne', 'DEF', 78, 'LB'], ['Ian Maatsen', 'DEF', 79, 'LB'],
    ['Boubacar Kamara', 'MID', 82, 'CDM'], ['Youri Tielemans', 'MID', 82, 'CM'], ['John McGinn', 'MID', 82, 'CM'],
    ['Morgan Rogers', 'MID', 83, 'CAM'], ['Amadou Onana', 'MID', 82, 'CDM'], ['Leon Bailey', 'MID', 81, 'RW'],
    ['Ollie Watkins', 'FWD', 85, 'ST'], ['Evann Guessand', 'FWD', 79, 'FWD'], ['Donyell Malen', 'FWD', 80, 'FWD'],
  ]},
  { id: 'tottenhamhotspur', name: 'Tottenham Hotspur', pts: 62, gf: 62, ga: 52, squad: [
    ['Guglielmo Vicario', 'GK', 83], ['Antonín Kinský', 'GK', 76],
    ['Cristian Romero', 'DEF', 85, 'CB'], ['Micky van de Ven', 'DEF', 84, 'CB'], ['Kevin Danso', 'DEF', 79, 'CB'],
    ['Pedro Porro', 'DEF', 83, 'RB'], ['Destiny Udogie', 'DEF', 81, 'LB'], ['Djed Spence', 'DEF', 79, 'RB'], ['Archie Gray', 'DEF', 79, 'CM'],
    ['Mohammed Kudus', 'MID', 83, 'RW'], ['Pape Matar Sarr', 'MID', 80, 'CM'], ['Rodrigo Bentancur', 'MID', 81, 'CM'],
    ['Lucas Bergvall', 'MID', 80, 'CM'], ['João Palhinha', 'MID', 83, 'CDM'], ['Xavi Simons', 'MID', 84, 'CAM'],
    ['Dominic Solanke', 'FWD', 82, 'ST'], ['Richarlison', 'FWD', 80, 'ST'], ['Brennan Johnson', 'FWD', 81, 'RW'], ['Son Heung-min', 'FWD', 85, 'LW'],
  ]},
  { id: 'brightonhovealbion', name: 'Brighton & Hove Albion', pts: 58, gf: 62, ga: 58, squad: [
    ['Bart Verbruggen', 'GK', 81], ['Jason Steele', 'GK', 74],
    ['Lewis Dunk', 'DEF', 82, 'CB'], ['Jan Paul van Hecke', 'DEF', 81, 'CB'], ['Adam Webster', 'DEF', 77, 'CB'],
    ['Ferdi Kadıoğlu', 'DEF', 80, 'LB'], ['Joël Veltman', 'DEF', 77, 'RB'], ['Maxim De Cuyper', 'DEF', 78, 'LB'],
    ['Carlos Baleba', 'MID', 83, 'CDM'], ['Mats Wieffer', 'MID', 80, 'CDM'], ['James Milner', 'MID', 74, 'CM'],
    ['Kaoru Mitoma', 'MID', 84, 'LW'], ['Yankuba Minteh', 'MID', 81, 'RW'], ['Diego Gómez', 'MID', 78, 'CM'],
    ['Georginio Rutter', 'FWD', 81, 'FWD'], ['Danny Welbeck', 'FWD', 80, 'ST'], ['João Pedro', 'FWD', 81, 'ST'], ['Stefanos Tzimas', 'FWD', 77, 'ST'],
  ]},
  { id: 'afcbournemouth', name: 'AFC Bournemouth', pts: 56, gf: 56, ga: 50, squad: [
    ['Đorđe Petrović', 'GK', 79], ['Mark Travers', 'GK', 74],
    ['Marcos Senesi', 'DEF', 80, 'CB'], ['Bafodé Diakité', 'DEF', 79, 'CB'], ['Adrien Truffert', 'DEF', 79, 'LB'],
    ['Julián Araujo', 'DEF', 78, 'RB'], ['Adam Smith', 'DEF', 75, 'RB'], ['James Hill', 'DEF', 76, 'CB'],
    ['Tyler Adams', 'MID', 80, 'CDM'], ['Ryan Christie', 'MID', 78, 'CM'], ['Lewis Cook', 'MID', 78, 'CM'],
    ['Alex Scott', 'MID', 78, 'CM'], ['Marcus Tavernier', 'MID', 79, 'LM'],
    ['Evanilson', 'FWD', 82, 'ST'], ['Antoine Semenyo', 'FWD', 83, 'RW'], ['Justin Kluivert', 'FWD', 81, 'LW'], ['Eli Junior Kroupi', 'FWD', 77, 'ST'],
  ]},
  { id: 'crystalpalace', name: 'Crystal Palace', pts: 55, gf: 52, ga: 50, squad: [
    ['Dean Henderson', 'GK', 81], ['Walter Benítez', 'GK', 76],
    ['Marc Guéhi', 'DEF', 83, 'CB'], ['Maxence Lacroix', 'DEF', 82, 'CB'], ['Chris Richards', 'DEF', 80, 'CB'],
    ['Daniel Muñoz', 'DEF', 82, 'RB'], ['Tyrick Mitchell', 'DEF', 80, 'LB'], ['Borna Sosa', 'DEF', 77, 'LB'],
    ['Adam Wharton', 'MID', 82, 'CM'], ['Will Hughes', 'MID', 76, 'CM'], ['Jefferson Lerma', 'MID', 80, 'CDM'],
    ['Daichi Kamada', 'MID', 80, 'CAM'], ['Ismaïla Sarr', 'MID', 82, 'RW'], ['Yéremy Pino', 'MID', 80, 'RW'],
    ['Jean-Philippe Mateta', 'FWD', 83, 'ST'], ['Eddie Nketiah', 'FWD', 78, 'ST'], ['Christantus Uche', 'FWD', 77, 'FWD'],
  ]},
  { id: 'brentford', name: 'Brentford', pts: 52, gf: 58, ga: 58, squad: [
    ['Caoimhín Kelleher', 'GK', 80], ['Hákon Valdimarsson', 'GK', 74],
    ['Nathan Collins', 'DEF', 81, 'CB'], ['Ethan Pinnock', 'DEF', 79, 'CB'], ['Sepp van den Berg', 'DEF', 78, 'CB'],
    ['Michael Kayode', 'DEF', 78, 'RB'], ['Rico Henry', 'DEF', 78, 'LB'], ['Aaron Hickey', 'DEF', 77, 'RB'],
    ['Christian Nørgaard', 'MID', 79, 'CDM'], ['Mathias Jensen', 'MID', 78, 'CM'], ['Yehor Yarmoliuk', 'MID', 77, 'CDM'],
    ['Mikkel Damsgaard', 'MID', 81, 'CAM'], ['Jordan Henderson', 'MID', 78, 'CM'], ['Kevin Schade', 'FWD', 80, 'LW'],
    ['Igor Thiago', 'FWD', 80, 'ST'], ['Dango Ouattara', 'FWD', 79, 'RW'], ['Fábio Carvalho', 'FWD', 78, 'CAM'],
  ]},
  { id: 'fulham', name: 'Fulham', pts: 52, gf: 54, ga: 55, squad: [
    ['Bernd Leno', 'GK', 81], ['Benjamin Lecomte', 'GK', 74],
    ['Calvin Bassey', 'DEF', 80, 'CB'], ['Joachim Andersen', 'DEF', 80, 'CB'], ['Jorge Cuenca', 'DEF', 77, 'CB'],
    ['Kenny Tete', 'DEF', 78, 'RB'], ['Antonee Robinson', 'DEF', 82, 'LB'], ['Timothy Castagne', 'DEF', 79, 'RB'],
    ['Sander Berge', 'MID', 80, 'CM'], ['Sasa Lukic', 'MID', 78, 'CDM'], ['Tom Cairney', 'MID', 78, 'CM'],
    ['Emile Smith Rowe', 'MID', 80, 'CAM'], ['Harry Wilson', 'MID', 79, 'RW'], ['Alex Iwobi', 'MID', 81, 'LM'],
    ['Raúl Jiménez', 'FWD', 79, 'ST'], ['Rodrigo Muniz', 'FWD', 80, 'ST'], ['Adama Traoré', 'FWD', 79, 'RW'],
  ]},
  { id: 'everton', name: 'Everton', pts: 50, gf: 48, ga: 48, squad: [
    ['Jordan Pickford', 'GK', 84], ['Mark Travers', 'GK', 73],
    ['Jarrad Branthwaite', 'DEF', 82, 'CB'], ['James Tarkowski', 'DEF', 80, 'CB'], ['Michael Keane', 'DEF', 76, 'CB'],
    ['Vitalii Mykolenko', 'DEF', 79, 'LB'], ['Jake O\'Brien', 'DEF', 79, 'CB,RB'], ['Nathan Patterson', 'DEF', 77, 'RB'],
    ['Idrissa Gueye', 'MID', 79, 'CDM'], ['James Garner', 'MID', 78, 'CM'], ['Tim Iroegbunam', 'MID', 76, 'CM'],
    ['Dwight McNeil', 'MID', 80, 'LW'], ['Carlos Alcaraz', 'MID', 79, 'CAM'], ['Iliman Ndiaye', 'MID', 81, 'FWD'],
    ['Beto', 'FWD', 78, 'ST'], ['Thierno Barry', 'FWD', 78, 'ST'], ['Dominic Calvert-Lewin', 'FWD', 79, 'ST'],
  ]},
  { id: 'nottinghamforest', name: 'Nottingham Forest', pts: 50, gf: 54, ga: 54, squad: [
    ['Matz Sels', 'GK', 81], ['John Victor', 'GK', 76],
    ['Murillo', 'DEF', 83, 'CB'], ['Nikola Milenković', 'DEF', 82, 'CB'], ['Morato', 'DEF', 78, 'CB'],
    ['Ola Aina', 'DEF', 80, 'RB'], ['Neco Williams', 'DEF', 79, 'LB'], ['Nicolás Domínguez', 'DEF', 77, 'CDM'],
    ['Morgan Gibbs-White', 'MID', 83, 'CAM'], ['Elliot Anderson', 'MID', 82, 'CM'], ['Ibrahim Sangaré', 'MID', 80, 'CDM'],
    ['Douglas Luiz', 'MID', 81, 'CM'], ['Ryan Yates', 'MID', 77, 'CM'],
    ['Chris Wood', 'FWD', 81, 'ST'], ['Igor Jesus', 'FWD', 78, 'ST'], ['Callum Hudson-Odoi', 'FWD', 80, 'LW'], ['Dan Ndoye', 'FWD', 81, 'RW'],
  ]},
  { id: 'westhamunited', name: 'West Ham United', pts: 44, gf: 48, ga: 62, squad: [
    ['Alphonse Areola', 'GK', 79], ['Mads Hermansen', 'GK', 78],
    ['Max Kilman', 'DEF', 80, 'CB'], ['Jean-Clair Todibo', 'DEF', 80, 'CB'], ['Konstantinos Mavropanos', 'DEF', 78, 'CB'],
    ['Aaron Wan-Bissaka', 'DEF', 80, 'RB'], ['El Hadji Malick Diouf', 'DEF', 78, 'LB'], ['Emerson', 'DEF', 78, 'LB'],
    ['Lucas Paquetá', 'MID', 82, 'CAM'], ['Tomáš Souček', 'MID', 79, 'CM'], ['James Ward-Prowse', 'MID', 80, 'CM'],
    ['Guido Rodríguez', 'MID', 78, 'CDM'], ['Mateus Fernandes', 'MID', 78, 'CM'],
    ['Jarrod Bowen', 'FWD', 84, 'RW,ST'], ['Crysencio Summerville', 'FWD', 81, 'LW'], ['Niclas Füllkrug', 'FWD', 79, 'ST'], ['Callum Wilson', 'FWD', 78, 'ST'],
  ]},
  { id: 'manchesterunited', name: 'Manchester United', pts: 44, gf: 50, ga: 54, squad: [
    ['Senne Lammens', 'GK', 79], ['Altay Bayındır', 'GK', 76],
    ['Matthijs de Ligt', 'DEF', 84, 'CB'], ['Lisandro Martínez', 'DEF', 83, 'CB'], ['Leny Yoro', 'DEF', 82, 'CB'],
    ['Noussair Mazraoui', 'DEF', 81, 'RB'], ['Diogo Dalot', 'DEF', 81, 'RB,LB'], ['Luke Shaw', 'DEF', 80, 'LB'], ['Harry Maguire', 'DEF', 79, 'CB'],
    ['Bruno Fernandes', 'MID', 87, 'CAM'], ['Manuel Ugarte', 'MID', 80, 'CDM'], ['Kobbie Mainoo', 'MID', 81, 'CM'],
    ['Casemiro', 'MID', 79, 'CDM'], ['Amad Diallo', 'MID', 82, 'RW'], ['Mason Mount', 'MID', 80, 'CAM'],
    ['Matheus Cunha', 'FWD', 84, 'FWD'], ['Bryan Mbeumo', 'FWD', 84, 'RW'], ['Benjamin Šeško', 'FWD', 82, 'ST'], ['Joshua Zirkzee', 'FWD', 79, 'ST'],
  ]},
  { id: 'wolverhamptonwanderers', name: 'Wolverhampton Wanderers', pts: 40, gf: 48, ga: 66, squad: [
    ['José Sá', 'GK', 79], ['Sam Johnstone', 'GK', 77],
    ['Toti Gomes', 'DEF', 78, 'CB'], ['Santiago Bueno', 'DEF', 77, 'CB'], ['Ladislav Krejčí', 'DEF', 79, 'CB'], ['Emmanuel Agbadou', 'DEF', 78, 'CB'],
    ['Nélson Semedo', 'DEF', 78, 'RB'], ['Hugo Bueno', 'DEF', 76, 'LB'],
    ['João Gomes', 'MID', 81, 'CM'], ['André', 'MID', 79, 'CDM'], ['Jean-Ricner Bellegarde', 'MID', 79, 'CAM'],
    ['Marshall Munetsi', 'MID', 78, 'CM'], ['Tolu Arokodare', 'FWD', 78, 'ST'],
    ['Jørgen Strand Larsen', 'FWD', 81, 'ST'], ['Hwang Hee-chan', 'FWD', 79, 'FWD'], ['Jhon Arias', 'FWD', 80, 'RW'],
  ]},
  { id: 'leedsunited', name: 'Leeds United', pts: 38, gf: 44, ga: 60, squad: [
    ['Lucas Perri', 'GK', 79], ['Karl Darlow', 'GK', 73],
    ['Joe Rodon', 'DEF', 78, 'CB'], ['Pascal Struijk', 'DEF', 78, 'CB'], ['Jaka Bijol', 'DEF', 79, 'CB'],
    ['Jayden Bogle', 'DEF', 78, 'RB'], ['Junior Firpo', 'DEF', 77, 'LB'], ['Gabriel Gudmundsson', 'DEF', 77, 'LB'],
    ['Ethan Ampadu', 'MID', 79, 'CDM'], ['Ao Tanaka', 'MID', 78, 'CM'], ['Anton Stach', 'MID', 79, 'CM'],
    ['Brenden Aaronson', 'MID', 78, 'CAM'], ['Sean Longstaff', 'MID', 77, 'CM'], ['Daniel James', 'MID', 78, 'RW'],
    ['Lukas Nmecha', 'FWD', 78, 'ST'], ['Joël Piroe', 'FWD', 78, 'ST'], ['Noah Okafor', 'FWD', 78, 'LW'],
  ]},
  { id: 'burnley', name: 'Burnley', pts: 33, gf: 38, ga: 64, squad: [
    ['Martin Dúbravka', 'GK', 78], ['Václav Hladký', 'GK', 73],
    ['Maxime Estève', 'DEF', 76, 'CB'], ['Joe Worrall', 'DEF', 75, 'CB'], ['Hjalmar Ekdal', 'DEF', 74, 'CB'],
    ['Kyle Walker', 'DEF', 79, 'RB'], ['Quilindschy Hartman', 'DEF', 76, 'LB'], ['Connor Roberts', 'DEF', 74, 'RB'],
    ['Josh Cullen', 'MID', 77, 'CDM'], ['Josh Brownhill', 'MID', 77, 'CM'], ['Lesley Ugochukwu', 'MID', 78, 'CM'],
    ['Florentino Luís', 'MID', 78, 'CDM'], ['Jacob Bruun Larsen', 'MID', 75, 'RW'],
    ['Lyle Foster', 'FWD', 76, 'ST'], ['Zian Flemming', 'FWD', 76, 'FWD'], ['Jaidon Anthony', 'FWD', 76, 'LW'],
  ]},
  { id: 'sunderland', name: 'Sunderland', pts: 30, gf: 36, ga: 66, squad: [
    ['Robin Roefs', 'GK', 77], ['Anthony Patterson', 'GK', 75],
    ['Dan Ballard', 'DEF', 77, 'CB'], ['Omar Alderete', 'DEF', 77, 'CB'], ['Nordi Mukiele', 'DEF', 78, 'CB,RB'],
    ['Trai Hume', 'DEF', 77, 'RB'], ['Reinildo Mandava', 'DEF', 77, 'LB'], ['Lutsharel Geertruida', 'DEF', 78, 'RB'],
    ['Granit Xhaka', 'MID', 82, 'CDM'], ['Noah Sadiki', 'MID', 77, 'CM'], ['Habib Diarra', 'MID', 78, 'CM'],
    ['Enzo Le Fée', 'MID', 79, 'CAM'], ['Chemsdine Talbi', 'MID', 76, 'RW'],
    ['Wilson Isidor', 'FWD', 78, 'ST'], ['Brian Brobbey', 'FWD', 78, 'ST'], ['Simon Adingra', 'FWD', 78, 'LW'],
  ]},
];
